project:
  type: website
    
website:
  title: Susmi Sharma
  navbar:
     left:
      - href: index.html
        text: Home
      - text: Projects
        menu:
        - href: ProjectCode.html
          text: Model Code (Knowledge Mining)
        - href: DataMining_Project.pdf
          text: Presentation Slides (Knowledge Mining)
        - href: CVD_RandomForest.pdf
          text: Cardiovascular Disease Paper (Knowledge Mining)
        - href: ACN Project Presentation Final.pdf
          text: Presentation Slides (Computational Modeling Method in BBS)
      - href: SusmiSharmaResume_2025.pdf
        text: CV
      - text: Assignments
        menu:
        - href: Lab01.html
          text: lab01
        - href: Lab02.html
          text: Lab02
        - href: Assignment2.html
          text: Assignment2   
        - href: Lab03.html
          text: Lab03
        - href: Assignment3.html
          text: Assignment3  
        - href: Lab04_UL.html
          text: Lab04
        - href: Lab_linearregression01.html
          text: Linear regression
        - href: Assignment6.html
          text: Assignment6
        - href: Lab_logisticregression01.html
          text: Logistic regression
        - href: Assignment7.html
          text: Assignment7 
        - href: Assignment8.html
          text: Assignment8
        - href: Lab_LDA01.html
          text: LDA
  

format: 
  html:
    theme: Yeti
    css: styles.css
    toc: true

editor: visual

