project:
  type: website
    
website:
  title: Susmi Sharma
  navbar:
     left:
      - href: index.html
        text: Home
      - text: Knowledge Mining Project
        menu:
        - href: ProjectCode.html
          text: RF_Model_2_Code
      - text: Assignments
        menu:
        - href: Lab01.html
          text: Assignment1
        - href: Lab02.html
          text: Assignment2

format: 
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

