project:
  type: website
  output-dir: docs
    
website:
  title: "Susmi Sharma"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Assignments
        menu:
        - href: Lab01.qmd
          text: Assignment1

format: 
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

